Rails.application.routes.draw do
  get "pages/home"
  get "pages/users"
  get "pages/admin"
  devise_for :admins, controllers: {
    sessions: "admin/sessions",
    registrations: "admin/registrations"
  }
  devise_for :users, controller: {
    sessions: "users/sessions"
  }
  # # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # # Defines the root path route ("/")
  # root "posts#index"

  resources :posts do
    post :export, on: :collection
    resources :comments
    collection do
      get :download_excel          # Normal Excel download (immediate)
      post :generate_excel         # Triggers Sidekiq job to generate Excel in the background
      # post :download_generated_excel # Downloads the Excel file generated by Sidekiq
      get :download_pdf
      get :download_image
    end
  end
  get 'download_pie_chart', to: 'posts#download_pie_chart'
  get "download_generated_excel", to: "posts#download_generated_excel", as: "download_generated_excel"

  resources :users
  root "posts#index"
  # root "pages#home"
end
